//
//  JournalEntryRecord.swift
//  Novi
//
//  SwiftData model for a saved journal entry and its generated lesson.
//

import Foundation
import SwiftData

/// A journal entry the user is writing or has saved, together with the
/// translation and lesson generated for it.
///
/// Each entry is an auto-saved document (notes-app style): the editor binds
/// directly to these properties and SwiftData persists every change.
@Model
final class JournalEntryRecord {
    @Attribute(.unique) var id: UUID
    var createdAt: Date
    /// Last time the entry changed — drives the "last saved" label and sorting.
    var updatedAt: Date

    /// User-provided title; auto-generated by AI when left empty.
    ///
    /// Property-level defaults are required so SwiftData can lightweight-migrate
    /// existing stores when new attributes are added.
    var title: String = ""

    var sourceText: String = ""
    var sourceLanguage: String = "auto"
    var targetLanguage: String = "en"

    /// The Tier-1 live translation, kept in sync as the user writes.
    var liveTranslation: String = ""
    /// The lesson's own translation (may be empty for AI lessons).
    var lessonTranslation: String = ""

    var grammarNotes: [String] = []
    var writingChallenge: String = ""

    @Relationship(deleteRule: .cascade, inverse: \VocabularyItemRecord.entry)
    var vocabulary: [VocabularyItemRecord]

    /// Library words that appeared in this entry (many-to-many). Deleting the
    /// entry only unlinks the words, it doesn't delete them.
    @Relationship(deleteRule: .nullify, inverse: \WordRecord.entries)
    var words: [WordRecord] = []

    init(
        id: UUID = UUID(),
        createdAt: Date = Date(),
        updatedAt: Date? = nil,
        title: String = "",
        sourceText: String = "",
        sourceLanguage: String = "auto",
        targetLanguage: String = "en",
        liveTranslation: String = "",
        lessonTranslation: String = "",
        grammarNotes: [String] = [],
        writingChallenge: String = "",
        vocabulary: [VocabularyItemRecord] = []
    ) {
        self.id = id
        self.createdAt = createdAt
        self.updatedAt = updatedAt ?? createdAt
        self.title = title
        self.sourceText = sourceText
        self.sourceLanguage = sourceLanguage
        self.targetLanguage = targetLanguage
        self.liveTranslation = liveTranslation
        self.lessonTranslation = lessonTranslation
        self.grammarNotes = grammarNotes
        self.writingChallenge = writingChallenge
        self.vocabulary = vocabulary
    }

    // MARK: - Display helpers (not persisted)

    /// Title to show in the sidebar: the user/AI title, else a text preview.
    var displayTitle: String {
        let trimmedTitle = title.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmedTitle.isEmpty { return trimmedTitle }
        let firstLine = sourceText
            .components(separatedBy: .newlines)
            .first?
            .trimmingCharacters(in: .whitespaces) ?? ""
        return firstLine.isEmpty ? "New Entry" : String(firstLine.prefix(50))
    }

    /// True when the entry has no content worth keeping (used to prune
    /// abandoned empty notes).
    var isEmpty: Bool {
        title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            && sourceText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            && liveTranslation.isEmpty
            && lessonTranslation.isEmpty
            && grammarNotes.isEmpty
            && writingChallenge.isEmpty
            && vocabulary.isEmpty
    }
}
